### ISSUE TITLE
Slow 50-config step

### ISSUE THREAD

**Issue by saward** [linuxserver/docker-grav#10]
Not sure what's going on, it ran fine on my local machine, but now that I'm trying in a k3s single node cluster, it seems to be getting stuck on something with the '50-config: executing...' step.  Any ideas what might be going on to cause this to be slow?

The config itself is pretty basic.

## Expected Behavior

Startup takes 30 seconds or so.

## Current Behavior

Startup takes 5 or 10 minutes or so to start up.

## Environment
**OS:** Linux base (Ubuntu)
**CPU architecture:** x86 64bit
**How docker service was installed:** Using k3s to run the image

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Grav: https://opencollective.com/grav/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
```
Config used for k3s:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-cms-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-cms
  template:
    metadata:
      labels:
        app: base-cms
    spec:
      containers:
        - name: base-cms
          image: lscr.io/linuxserver/grav
          ports:
          - containerPort: 80
          imagePullPolicy: IfNotPresent
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Australia/Melbourne"
          volumeMounts:
            - name: cms-data
              mountPath: /config
      volumes:
        - name: cms-data
          persistentVolumeClaim:
            claimName: base-cms-pvc
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: base-cms-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: base-cms
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-cms-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: base-cms-service
            port:
              number: 80
```
